packages/renderers-js/src/fragments/instructionFunction.ts

Fix an error in the JS renderer that causes a `Cannot find name 'args'` error.
This is because when an instruction has no arguments, the `args` variable won't be generated. However, when an instruction has remaining accounts that rely on the `argumentValueNode`, then we need that variable to exist.
The fix is to update the value of the `hasAnyArgs` helper to also include `remainingAccountsNodes` of values `argumentValueNode`.

Fix missing args variable error in JS renderer

---

.changeset/weak-coats-relate.md
packages/renderers-js/src/fragments/instructionFunction.ts
packages/renderers-js/src/utils/async.ts
packages/renderers-js/test/_setup.ts
packages/renderers-js/test/instructionsPage.test.ts
packages/visitors-core/src/getResolvedInstructionInputsVisitor.ts

Prior to this PR, a TypeScript/Lint "unused variable" warning was created on the synchronous function of generated instruction helpers if the all of the following conditions were true:
- Your instruction used `extraArguments` but no `arguments`.
- Your instruction used an async `resolver`.
This PR fixes this.

Fix unused args variable on sync instruction functions on JS renderer

---

.changeset/good-apricots-sell.md
packages/renderers-rust/e2e/memo/src/generated/instructions/add_memo.rs
packages/renderers-rust/e2e/system/src/generated/instructions/advance_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/authorize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/initialize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/upgrade_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/withdraw_nonce_account.rs
packages/renderers-rust/public/templates/instructionsPage.njk
packages/renderers-rust/test/instructionsPage.test.ts

This PR adds a `Default` impl for instruction data structs.

Add default impl for instruction data struct

---

.changeset/hip-years-clean.md
packages/nodes-from-anchor/src/v01/ProgramNode.ts
packages/nodes-from-anchor/test/v01/ProgramNode.test.ts

resolves https://github.com/kinobi-so/kinobi/issues/36
- Remove types from the anchor idl that match up with accounts before generating definedTypes.

Remove Anchor V01 Accounts from Defined Types

---

.changeset/afraid-experts-give.md
packages/visitors-core/src/LinkableDictionary.ts

This PR adds the implementation for `getOrThrow`, which seems to be missing. Without this, using defined types as arguments for instructions fails.

Add getOrThrow implementation

---

.changeset/tasty-rocks-sleep.md
packages/node-types/src/PdaNode.ts
packages/node-types/src/contextualValueNodes/PdaValueNode.ts
packages/nodes/src/PdaNode.ts
packages/nodes/src/contextualValueNodes/PdaValueNode.ts
packages/renderers-js-umi/src/renderInstructionDefaults.ts
packages/renderers-js-umi/test/instructionsPage.test.ts
packages/renderers-js/src/fragments/instructionInputDefault.ts
packages/visitors/src/fillDefaultPdaSeedValuesVisitor.ts

As discussed in PR #42, this PR allows `PdaValueNodes` to define their own `PdaNode` instead of requiring a top-level `PdaNode` to exist on the program.
Renderers have been updated such that, when coming across a `PdaValueNode` with an inlined `PdaNode`, it won't try to import a generated PDA function but instead, will derive the PDA in situ.
Both JavaScript renderers have been updated. The Rust renderer currently doesn't use this information which is why this PR doesn't contain any changes in the Rust renderer.

Allow PdaValueNode to inline their own PdaNode definition

---

.changeset/soft-dragons-run.md
packages/renderers-rust/e2e/memo/Cargo.lock
packages/renderers-rust/e2e/memo/Cargo.toml
packages/renderers-rust/e2e/system/Cargo.lock
packages/renderers-rust/e2e/system/Cargo.toml
packages/renderers-rust/e2e/system/src/generated/accounts/nonce.rs
packages/renderers-rust/public/templates/accountsPage.njk
packages/renderers-rust/test/accountsPage.test.ts

This PR adds Anchor traits impl to account types so they can be directly referenced in structs annotated with `#[account]` in Anchor programs.
This provides basic validation that:
1. the account must be initialized; and
2. it has the correct owner.

Add anchor traits impl for accounts

---

.changeset/polite-cats-wash.md
packages/renderers-js/public/templates/fragments/pdaFunction.njk
packages/renderers-js/src/fragments/pdaFunction.ts
packages/renderers-js/test/pdasPage.test.ts

PDA helpers should generate PDA's with a default programAddress set to the provided PDA nodes' programId if programId is defined. If not defined, the default programAddress should be the encapsulating program node programId.
With this PR, the following test passes. All tests are passing locally. A changeset has been included.
```ts
test('it renders a PDA helper function with a default program address', async () => {
// Given the following PDA node with a default program address.
const node = programNode({
name: 'myProgram',
pdas: [
pdaNode({
name: 'foo',
programId: 'myProgramId',
seeds: [constantPdaSeedNodeFromString('utf8', 'myPrefix')],
}),
],
publicKey: '1111',
});
// When we render it.
const renderMap = visit(node, getRenderMapVisitor());
// Then we expect the following PDA function …
```

fix: render PDA helper with programAddress = node.programId if defined 

---

.changeset/shy-points-march.md
packages/renderers-js/src/ImportMap.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-js/test/accountsPage.test.ts

This PR modifies the `ImportMap` to filter out `type Type` variants from imports when the import for `Type` is present.
Instead of rendering with a duplicated import of `Key`:
```typescript
import { Key, getKeyDecoder, getKeyEncoder, type Key } from '../types';
```
The renderer will output:
```typescript
import { Key, getKeyDecoder, getKeyEncoder } from '../types';
```

Filter out type variant on imports

---

.changeset/proud-mugs-thank.md
packages/renderers-rust/e2e/memo/Cargo.lock
packages/renderers-rust/e2e/memo/Cargo.toml
packages/renderers-rust/e2e/system/Cargo.lock
packages/renderers-rust/e2e/system/Cargo.toml
packages/renderers-rust/e2e/system/src/generated/accounts/nonce.rs
packages/renderers-rust/public/templates/accountsPage.njk

This PR adds `impl` of `IdlBuild` and `Discriminator` traits for account types used by the idl-build feature.

Add support to Anchor idl build for account types

---

.changeset/little-planes-poke.md
packages/renderers-rust/src/renderVisitor.ts

Projects using Kinobi may configure their `rustfmt.toml` to use nightly-only
formatting configurations.
Currently, Kinobi always uses the stable toolchain when running `cargo fmt`
upon generating Rust client code.
Add an option to `RenderOptions` for Rust toolchain, allowing users to configure
a Rust toolchain for formatting.

Rust Renderer: Add toolchain arg to formatter

---

.changeset/small-jars-play.md
packages/nodes-from-anchor/src/v01/InstructionAccountNode.ts
packages/nodes-from-anchor/test/v01/ProgramNode.test.ts

- Convert name to camel case before searching argument node list as kinobi tracks all names in camel case format.

Fix Arg Lookup for Anchor V01 Seed Default Value Generation

---

.changeset/happy-bottles-cover.md
packages/renderers-js-umi/package.json
packages/renderers-js-umi/src/utils/codecs.ts
packages/renderers-js/e2e/anchor/package.json
packages/renderers-js/e2e/anchor/pnpm-lock.yaml
packages/renderers-js/e2e/memo/package.json
packages/renderers-js/e2e/memo/pnpm-lock.yaml
packages/renderers-js/e2e/system/package.json
packages/renderers-js/e2e/system/pnpm-lock.yaml
packages/renderers-js/e2e/token/package.json
packages/renderers-js/e2e/token/pnpm-lock.yaml
packages/renderers-js/e2e/token/src/generated/accounts/mint.ts
packages/renderers-js/e2e/token/src/generated/accounts/token.ts
packages/renderers-js/package.json
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-js/src/utils/codecs.ts
packages/renderers-js/test/types/zeroableOption.test.ts
packages/renderers-rust/package.json
packages/renderers-rust/src/utils/codecs.ts
pnpm-lock.yaml

This PR updates all references of web3.js in renderers to the latest technological preview version `tp4`.
For the `@kinobi-so/renderers-js` package, this means updating generated code to comply with the new version.
For the other renderers, this is just a bump of `@solana/codecs-string` that they use under the hood to convert bytes to and from strings of various encoding.

Update renderers to tp4 of web3.js

---

.changeset/tame-files-wash.md
.github/workflows/main.yml
packages/errors/src/codes.ts
packages/errors/src/context.ts
packages/errors/src/messages.ts
packages/node-types/src/typeNodes/RemainderOptionTypeNode.ts
packages/node-types/src/typeNodes/TypeNode.ts
packages/node-types/src/typeNodes/index.ts
packages/nodes/README.md
packages/nodes/docs/typeNodes/README.md
packages/nodes/docs/typeNodes/RemainderOptionTypeNode.md
packages/nodes/src/typeNodes/RemainderOptionTypeNode.ts
packages/nodes/src/typeNodes/TypeNode.ts
packages/nodes/src/typeNodes/index.ts
packages/nodes/test/typeNodes/RemainderOptionTypeNode.test.ts
packages/renderers-js-umi/src/getTypeManifestVisitor.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-js/test/types/remainderOption.test.ts
packages/renderers-rust/src/getTypeManifestVisitor.ts
packages/visitors-core/src/identityVisitor.ts
packages/visitors-core/src/mergeVisitor.ts
packages/visitors-core/test/nodes/typeNodes/RemainderOptionTypeNode.test.ts

This PR adds a node that represents an optional item using a child `TypeNode`. The item can either be present — i.e. `Some<T>` — or absent — i.e. `None` — depending on whether or not there are remaining bytes in the buffer.
Closes https://github.com/kinobi-so/kinobi/issues/59 using Option 1 described there. This is because Option 2 can be achieved in a better way using composable `BooleanTypeNodes` but this needs a whole refactoring anyway so we can delay that to later.
---
Side note: This PR also updates the main CI workflow so that it gets executed on any stacked PRs, not just the ones that target the `main` branch directly.

Add `RemainderOptionTypeNode`

---

.changeset/tasty-lamps-marry.md
packages/renderers-js/e2e/anchor/src/generated/errors/wenTransferGuard.ts
packages/renderers-js/e2e/system/src/generated/errors/system.ts
packages/renderers-js/e2e/system/test/transferSol.test.ts
packages/renderers-js/e2e/token/src/generated/errors/associatedToken.ts
packages/renderers-js/e2e/token/src/generated/errors/token.ts
packages/renderers-js/public/templates/fragments/programErrors.njk
packages/renderers-js/src/ImportMap.ts
packages/renderers-js/src/fragments/programErrors.ts
packages/renderers-js/src/nameTransformers.ts

This PR generates a new helper function in the JS renderer that wraps `isProgramError` from `@solana/programs` such that, the error code type is known and the program address must not be provided.
Here's an example using the system program.
```ts
// Before.
isProgramError(error, txMessage, SYSTEM_PROGRAM_ADDRESS, SYSTEM_ERROR__ACCOUNT_ALREADY_IN_USE);
// After.
isSystemError(error, txMessage, SYSTEM_ERROR__ACCOUNT_ALREADY_IN_USE);
```
Here's another example without passing an explicit code expectation. For it to work with `isProgramError` a type parameter must be provided. With the generated helper, this is no longer needed.
```ts
// Before.
isProgramError<SystemError>(error, txMessage, SYSTEM_PROGRAM_ADDRESS);
// After.
isSystemError(error, txMessage);
```

Add isProgramError helper in JS renderer

---

.changeset/shaggy-shrimps-call.md
packages/renderers-js/e2e/anchor/src/generated/programs/wenTransferGuard.ts
packages/renderers-js/e2e/system/src/generated/programs/system.ts
packages/renderers-js/e2e/token/src/generated/programs/associatedToken.ts
packages/renderers-js/e2e/token/src/generated/programs/system.ts
packages/renderers-js/e2e/token/src/generated/programs/token.ts
packages/renderers-js/src/fragments/programAccounts.ts
packages/renderers-js/src/fragments/programInstructions.ts
packages/renderers-js/test/programsPage.test.ts

The `identifyXInstruction` and `identifyXAccount` already accept a `Uint8Array` that can be used to identify an instruction given just the data byte array. But if this comes from a web3js encoder (eg encoding base64 data from somewhere else), then the datatype will be `ReadonlyUint8Array` instead. 
This PR updates these identify functions to allow an input of `ReadonlyUint8Array` instead. This doesn't require any further changes, as everything being done with data is already compatible with `ReadonlyUint8Array`. It's also backward compatible, you can still pass a `Uint8Array` in. 
This means that output from our encoders can now be passed directly to these generated instructions.

Use ReadonlyUint8Array for identifying accounts/instructions by data

---

.changeset/brave-pens-float.md
packages/renderers-rust/src/getTypeManifestVisitor.ts
packages/renderers-rust/test/types/array.test.ts
packages/renderers-rust/test/types/number.test.ts

Currently, the Rust renderer can only render `DefinedTypeNodes` if the child type is a `StructTypeNode` or an `EnumTypeNode`.
This PR allows any other child type to be rendered as a Rust type alias like so.
```rust
pub type MyAlias = ShortVec<Pubkey>;
```

Support type aliases from DefinedTypeNodes in Rust renderer

---

.changeset/cyan-badgers-stare.md
packages/renderers-js/e2e/system/idl.json
packages/renderers-js/e2e/system/src/generated/accounts/nonce.ts
packages/renderers-js/e2e/system/src/generated/instructions/createAccount.ts
packages/renderers-js/e2e/token/idl.json
packages/renderers-js/e2e/token/src/generated/instructions/createAccount.ts
packages/renderers-js/src/ImportMap.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-js/test/types/solAmount.test.ts

Note:  #160 is a prerequisite (Graphite 💔)
This PR updates how `SolAmountTypeNode` is rendered in the new web3js renderer. Previously it just rendered its nested number type. It now renders with a `Lamports` type from web3js. The encoder + decoder use `getLamportsEncoder` and `getLamportsDecoder`, passing the nested number encoder/decoder as an argument.
This means that you can represent Lamports in the Kinobi IDL using any numeric type, and you'll get properly typed Lamports back. This can improve eg parsing of instructions like `createAccount` where some arguments represent Lamport values.

Render sol amount as lamports

---

.changeset/tasty-laws-admire.md
packages/visitors-core/README.md
packages/visitors-core/src/index.ts
packages/visitors-core/src/interceptFirstVisitVisitor.ts
packages/visitors-core/test/interceptFirstVisitVisitor.test.ts

This PR adds a new visitor primitive called `interceptFirstVisitVisitor`.
It works the same way as the `interceptVisitor` primitive but only intercepts the first visit of a node. This means that the provided function is called when visiting the specific node provided but not when visiting its children. The parameters are the same as for the `interceptVisitor`.
For instance, the following visitor intercepts a `voidVisitor` and captures events only during the first visit.
```ts
const events: string[] = [];
const visitor = interceptFirstVisitVisitor(voidVisitor(), (node, next) => {
events.push(`down:${node.kind}`);
next(node);
events.push(`up:${node.kind}`);
});
visit(tupleTypeNode([numberTypeNode('u32'), publicKeyTypeNode()]), visitor);
// events === [
//     'down:tupleTypeNode',
// …
```

Add `interceptFirstVisitVisitor` helper

---

.changeset/clever-news-worry.md
packages/visitors-core/src/LinkableDictionary.ts
packages/visitors-core/src/recordLinkablesVisitor.ts
packages/visitors-core/test/recordLinkablesVisitor.test.ts

This PR makes the `recordLinkablesVisitor` more robust by visiting the entire tree once before the first visit.
This ensure that we have access to every possible linkables in the tree instead of relying on the ones that are present before the current visit.

Record linkables before the first visit

---

.changeset/tough-grapes-give.md
packages/errors/src/context.ts
packages/node-types/src/linkNodes/AccountLinkNode.ts
packages/node-types/src/linkNodes/DefinedTypeLinkNode.ts
packages/node-types/src/linkNodes/PdaLinkNode.ts
packages/nodes/docs/linkNodes/AccountLinkNode.md
packages/nodes/docs/linkNodes/DefinedTypeLinkNode.md
packages/nodes/docs/linkNodes/PdaLinkNode.md
packages/nodes/src/linkNodes/AccountLinkNode.ts
packages/nodes/src/linkNodes/DefinedTypeLinkNode.ts
packages/nodes/src/linkNodes/PdaLinkNode.ts
packages/visitors-core/README.md
packages/visitors-core/src/LinkableDictionary.ts
packages/visitors-core/src/NodeStack.ts
packages/visitors-core/src/getDebugStringVisitor.ts
packages/visitors-core/src/recordLinkablesVisitor.ts
packages/visitors-core/test/nodes/linkNodes/AccountLinkNode.test.ts
packages/visitors-core/test/nodes/linkNodes/DefinedTypeLinkNode.test.ts
packages/visitors-core/test/nodes/linkNodes/PdaLinkNode.test.ts
packages/visitors-core/test/recordLinkablesVisitor.test.ts
packages/visitors/src/unwrapDefinedTypesVisitor.ts
packages/visitors/test/fillDefaultPdaSeedValuesVisitor.test.ts

This PR adds a new optional `program` attribute of type `ProgramLinkNode` to the other link nodes — i.e. `AccountLinkNode`, `DefinedTypeLinkNode` and `PdaLinkNode`.
This means, link nodes can now explicitly target another program instead of putting every linkable nodes within the same namespace, regardless of which program they belong to.
As such, the `LinkableDictionary` and the `recordLinkablesVisitor` have been updated to explicitly record linkable nodes and resolve link nodes from the program they belong to.
To illustrate all of that here's an example. Consider the following root node:
```ts
const programA = programNode({
accounts: [accountNode({ name: 'accountA' })],
definedTypes: [definedTypeNode({ name: 'someType', type: numberTypeNode('u32') })],
name: 'programA',
publicKey: …
```

[0.22] Add optional program attribute to link nodes

---

.changeset/two-swans-shake.md
packages/library/src/kinobi.ts
packages/library/test/index.test.ts

This PR fixes the type expectations for the visitor argument of the `kinobi.accept` and `kinobi.update` functions.

[0.21] Fix TS bug on `accept` and `update` Kinobi functions

---

.changeset/giant-dogs-scream.md
packages/renderers-js/src/fragments/common.ts
packages/renderers-js/test/_setup.ts
packages/renderers-js/test/pdasPage.test.ts

Currently, if you pass the same `ImportMap` to two fragments using the `fragment` function, each of these separate fragments will reference the same `ImportMap` instance. This causes other bugs as, when we update the imports of one fragments, we end up updating the imports of another.
This PR fixes this by cloning the `ImportMap` when creating a new fragment.

[0.21] Fix a bug that reuses the same `ImportMap` in fragments

---

.changeset/popular-cooks-dance.md
.github/workflows/main.yml

This PR adds a **major** changeset for all packages such that the "Publish packages" publishes all codama packages as version `1.0.0`.

Release all codama packages as v1

---

.changeset/many-rules-peel.md
packages/renderers-rust/src/getTypeManifestVisitor.ts
packages/renderers-rust/test/types/array.test.ts

Currently, when generating Rust types that are not enums or structs, the semicolon at the end of the statement is missing. This PR fixes this.
```rs
// Before.
pub type MyShortVec = ShortVec<Pubkey>
// After.
pub type MyShortVec = ShortVec<Pubkey>;
```

Fix missing semicolon in generated Rust code

---

.changeset/spicy-spoons-worry.md
packages/renderers-rust/README.md
packages/renderers-rust/src/getRenderMapVisitor.ts
packages/renderers-rust/src/getTypeManifestVisitor.ts
packages/renderers-rust/src/utils/index.ts
packages/renderers-rust/src/utils/traitOptions.ts
packages/renderers-rust/test/utils/traitOptions.test.ts

This PR adds the following `TraitOptions` configuration object to the Rust renderer allowing users to tweak how traits are rendered in their clients.
```ts
export type TraitOptions = {
/** The default traits to implement for all types. */
baseDefaults?: string[];
/**
* The default traits to implement for data enums only — on top of the base defaults.
* Data enums are enums with at least one non-unit variant.
*/
dataEnumDefaults?: string[];
/**
* The mapping of feature flags to traits.
* For each entry, the traits will be rendered within a
* `#[cfg(feature = "feature_name", derive(Traits))]` attribute.
*/
featureFlags?: Record<string, string[]>;
/** The complete trait overrides of specific types. */
overrides?: Record<string, string[]>;
/**
* The default traits to implement for scalar …
```

Add options to configure how traits are rendered in Rust

---

.changeset/tidy-bananas-collect.md
packages/visitors-core/src/NodePath.ts
packages/visitors-core/src/NodeStack.ts
packages/visitors-core/src/index.ts

This PR introduces the `NodePath` type and adds the ability to save and restore stacks inside a "stack heap".

Introduce NodePath and heap inside NodeStack

---

.changeset/red-plants-collect.md
packages/errors/src/context.ts
packages/renderers-js-umi/src/getRenderMapVisitor.ts
packages/renderers-js-umi/src/getTypeManifestVisitor.ts
packages/renderers-js/src/fragments/accountPdaHelpers.ts
packages/renderers-js/src/fragments/instructionAccountTypeParam.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-rust/src/getRenderMapVisitor.ts
packages/validators/README.md
packages/validators/src/ValidationItem.ts
packages/validators/src/getValidationItemsVisitor.ts
packages/visitors-core/README.md
packages/visitors-core/src/LinkableDictionary.ts
packages/visitors-core/src/NodePath.ts
packages/visitors-core/src/NodeStack.ts
packages/visitors-core/src/getByteSizeVisitor.ts
packages/visitors-core/src/recordLinkablesVisitor.ts
packages/visitors-core/test/recordLinkablesVisitor.test.ts
packages/visitors/src/createSubInstructionsFromEnumArgsVisitor.ts
packages/visitors/src/fillDefaultPdaSeedValuesVisitor.ts
packages/visitors/src/unwrapDefinedTypesVisitor.ts
packages/visitors/src/unwrapTypeDefinedLinksVisitor.ts
packages/visitors/test/fillDefaultPdaSeedValuesVisitor.test.ts

This PR records and resolves `NodePaths` instead of `Nodes` in `LinkableDictionaries`. This means, we can now access the whole path from the nodes we resolve and, therefore, push that path within our current `NodeStack`.

Use NodePath in LinkableDictionary

---

packages/renderers-js/src/fragments/accountFetchHelpers.ts
packages/renderers-js/src/fragments/accountPdaHelpers.ts
packages/renderers-js/src/fragments/accountSizeHelpers.ts
packages/renderers-js/src/fragments/accountType.ts
packages/renderers-js/src/fragments/instructionAccountTypeParam.ts
packages/renderers-js/src/fragments/instructionByteDelta.ts
packages/renderers-js/src/fragments/instructionData.ts
packages/renderers-js/src/fragments/instructionExtraArgs.ts
packages/renderers-js/src/fragments/instructionFunction.ts
packages/renderers-js/src/fragments/instructionInputResolved.ts
packages/renderers-js/src/fragments/instructionInputType.ts
packages/renderers-js/src/fragments/instructionParseFunction.ts
packages/renderers-js/src/fragments/instructionRemainingAccounts.ts
packages/renderers-js/src/fragments/instructionType.ts
packages/renderers-js/src/fragments/pdaFunction.ts
packages/renderers-js/src/getRenderMapVisitor.ts

This PR refactors the JS renderer to use `NodePaths` in helper fragments.

Use NodePaths in renderers-js

---

packages/renderers-js/src/getRenderMapVisitor.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/validators/README.md
packages/validators/src/ValidationItem.ts
packages/validators/src/getValidationItemsVisitor.ts
packages/visitors-core/README.md
packages/visitors-core/src/NodePath.ts
packages/visitors-core/src/NodeSelector.ts
packages/visitors-core/src/NodeStack.ts
packages/visitors-core/src/recordLinkablesVisitor.ts
packages/visitors-core/test/bottomUpTransformerVisitor.test.ts
packages/visitors-core/test/recordNodeStackVisitor.test.ts
packages/visitors-core/test/topDownTransformerVisitor.test.ts
packages/visitors/src/updateAccountsVisitor.ts

This PR adds new `NodePath` helper functions and pushes some of the responsibilities from the `NodeStack` to the `NodePath`. The former is designed to be a mutable stack that updates as we traverse the tree, whereas the latter is designed to hold an immutable path of nodes finishing in a specific typed node.

Refactor NodeStack and NodePath

---

.changeset/gold-eyes-battle.md
packages/visitors-core/src/NodePath.ts
packages/visitors-core/src/NodeSelector.ts
packages/visitors-core/src/bottomUpTransformerVisitor.ts
packages/visitors-core/src/topDownTransformerVisitor.ts
packages/visitors-core/test/NodeSelector.test.ts
packages/visitors-core/test/bottomUpTransformerVisitor.test.ts
packages/visitors-core/test/topDownTransformerVisitor.test.ts
packages/visitors/src/setFixedAccountSizesVisitor.ts
packages/visitors/src/unwrapTupleEnumWithSingleStructVisitor.ts

This PR uses the new `NodePath` type inside `NodeSelector` types instead of using the combo `Node + NodeStack`.

Use NodePaths in NodeSelectors

---

.changeset/curly-berries-jog.md
packages/visitors/README.md
packages/visitors/src/fillDefaultPdaSeedValuesVisitor.ts
packages/visitors/src/setInstructionAccountDefaultValuesVisitor.ts
packages/visitors/src/updateInstructionsVisitor.ts
packages/visitors/test/fillDefaultPdaSeedValuesVisitor.test.ts

This PR refactors the `fillDefaultPdaSeedValuesVisitor` to use `NodePaths`.

Use NodePaths in fillDefaultPdaSeedValuesVisitor

---

.changeset/soft-beds-jam.md
packages/renderers-js-umi/src/getRenderMapVisitor.ts
packages/visitors-core/src/getByteSizeVisitor.ts
packages/visitors-core/test/getByteSizeVisitor.test.ts
packages/visitors/src/setFixedAccountSizesVisitor.ts

This PR fixes an issue in the `getByteSizeVisitor` where complex link node paths would be incorrectly resolved due to the fact that the `NodeStack` would follow in invalid path in the tree. The new methods to save and restore `NodePaths` inside the `NodeStack` help us fix this.

Fix LinkNode paths for getByteSizeVisitor

---

.changeset/healthy-zoos-share.md
packages/visitors/src/unwrapDefinedTypesVisitor.ts
packages/visitors/test/unwrapDefinedTypesVisitor.test.ts

This PR fixes an issue in the `unwrapDefinedTypesVisitor ` where complex link node paths would be incorrectly resolved due to the fact that the `NodeStack` would follow in invalid path in the tree. The new methods to save and restore `NodePaths` inside the `NodeStack` help us fix this.

Fix LinkNode paths for unwrapDefinedTypesVisitor

---

.changeset/dirty-onions-arrive.md
packages/renderers-js-umi/src/getRenderMapVisitor.ts
packages/renderers-js-umi/src/getTypeManifestVisitor.ts
packages/renderers-js/src/getRenderMapVisitor.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-js/test/links/definedType.test.ts

This PR fixes an issue in the JavaScript `getTypeManifestVisitors` where complex link node paths would be incorrectly resolved due to the fact that the `NodeStack` would follow in invalid path in the tree. The new methods to save and restore `NodePaths` inside the `NodeStack` help us fix this.

Fix LinkNode paths for getTypeManifestVisitor

---

packages/renderers-js-umi/src/getRenderMapVisitor.ts
packages/renderers-js-umi/src/getTypeManifestVisitor.ts
packages/renderers-js/src/getRenderMapVisitor.ts
packages/renderers-js/src/getTypeManifestVisitor.ts

This PR applies a small refactoring to the JavaScript `getTypeManifestVisitors` that enables them to use the same instead of the visitor.

Refactor JS type manifest visitors

---

.changeset/serious-fireants-rescue.md
packages/visitors/src/transformU8ArraysToBytesVisitor.ts

The current behaviour confuses devs because some `u8` arrays are being turned into `BytesTypeNode` but not others based on their size. This PR fixes this by transforming all fixed-size arrays of `u8` numbers into a `FixedSizeTypeNode` of `BytesTypeNode`.

Transform all u8 arrays by default

---

.changeset/orange-penguins-relate.md
packages/nodes/src/shared/stringCases.ts
packages/nodes/test/shared/stringCases.test.ts

Absorb all special characters when converting string cases

---

.changeset/silent-frogs-sing.md
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction1.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction2.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction3.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction4.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction5.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction6.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction7.rs
packages/renderers-rust/e2e/memo/src/generated/instructions/add_memo.rs
packages/renderers-rust/e2e/system/src/generated/instructions/advance_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/authorize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/initialize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/upgrade_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/withdraw_nonce_account.rs
packages/renderers-rust/public/templates/instructionsPage.njk
packages/renderers-rust/src/getRenderMapVisitor.ts
packages/renderers-rust/src/utils/traitOptions.ts

Use trait options for instruction data in rust renderer

---

.changeset/rich-nails-talk.md
packages/renderers-rust/e2e/system/src/generated/errors/system.rs
packages/renderers-rust/public/templates/errorsPage.njk

Many Rust client applications may wish to define functions generic over `solana_program::decode_error::DecodeError`, which conveniently converts from a `ProgramError::Custom` to the respective enum value using `FromPrimitive`.
This change adds that trait implementation to the Rust renderer.

renderer-rust: add decode-error trait to errors

---

package.json

This is set in `pnpm-workspace.yaml`.

Remove redundant pnpm workspace info

---

.github/dependabot.yml

Use dependabot to manage that new e2e workspace for the `renderers-js` package.

Setup dependabot on renderers-js e2e dependencies

---

.changeset/pretty-walls-hammer.md
packages/renderers-js/e2e/system/src/generated/accounts/nonce.ts
packages/renderers-js/e2e/system/src/generated/instructions/createAccount.ts
packages/renderers-js/e2e/token/src/generated/instructions/createAccount.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-js/test/types/solAmount.test.ts

Since we're now using the latest version of web3.js v2 (instead of `rc`), we need to adjust the `Lamports` type.

Update Lamports type from web3.js v2

---

.changeset/tiny-bikes-hug.md
packages/renderers-rust/e2e/dummy/Cargo.lock
packages/renderers-rust/e2e/dummy/Cargo.toml
packages/renderers-rust/e2e/memo/Cargo.lock
packages/renderers-rust/e2e/memo/Cargo.toml
packages/renderers-rust/e2e/system/Cargo.lock
packages/renderers-rust/e2e/system/Cargo.toml
packages/renderers-rust/src/getTypeManifestVisitor.ts

resolves #184
`serde(with = "serde_with::As::<serde_with::Bytes>"))` does not work for arrays >32 items but is currently added. This causes a compiler error. Theoretically serde_with's docs state that `serde(with = "serde_with::As::<[_, X]>"))` should work but couldn't get it to compile. I introduced `serde-big-array` to resolve the issues.
Downside of this is that it adds an extra dependency (but only with `serde` feature enabled)

bug: serde serialize/deserialize big arrays

---

README.md
packages/errors/src/cli/index.ts
packages/errors/src/codes.ts
packages/errors/src/context.ts
packages/errors/src/error.ts
packages/errors/src/message-formatter.ts
packages/errors/src/messages.ts
packages/errors/src/stack-trace.ts
packages/renderers-js/README.md
packages/visitors-core/src/pipe.ts

Update links to web3.js v2 so they point to the new repo.

Update web3.js v2 URLs

---

.changeset/heavy-moles-smell.md
packages/cli/package.json
packages/cli/src/utils/import.ts
packages/cli/src/utils/logs.ts
packages/errors/bin/cli.cjs
packages/errors/bin/cli.mjs
packages/errors/package.json
packages/internals/tsup.config.cli.ts
packages/library/bin/cli.cjs
packages/library/bin/cli.mjs
packages/library/src/cli/index.ts
pnpm-lock.yaml

This PR changes the way we export CLI binaries by using CJS instead of ESM so that dynamically importing modules (e.g. JavaScript config files or visitors) works for both CJS and ESM modules.
It also improves the error handling when failing to import a module.

Improve ESM and CJS support when importing modules in CLI

---

.changeset/nasty-dots-lie.md
packages/renderers-rust/e2e/anchor/src/generated/instructions/create_guard.rs
packages/renderers-rust/e2e/anchor/src/generated/instructions/execute.rs
packages/renderers-rust/e2e/anchor/src/generated/instructions/initialize.rs
packages/renderers-rust/e2e/anchor/src/generated/instructions/update_guard.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction1.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction2.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction3.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction4.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction5.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction6.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction7.rs
packages/renderers-rust/e2e/memo/src/generated/instructions/add_memo.rs
packages/renderers-rust/e2e/system/src/generated/instructions/advance_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/authorize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/initialize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/upgrade_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/withdraw_nonce_account.rs
packages/renderers-rust/public/templates/instructionsCpiPage.njk
packages/renderers-rust/public/templates/instructionsPage.njk

As described in #207 , `try_to_vec` was removed from `borsh` in versions `1.x`. This causes problems since the rust renderer generates code using it.
Replace the use of `try_to_vec` by `borsh::to_vec`, which is available in versions of `borsh` < `1`.
Fixes #207

renderers-rust: Use `borsh::to_vec`

---

.changeset/fuzzy-nails-wait.md
packages/nodes-from-anchor/src/v01/typeNodes/TypeNode.ts

Anchor will skip serializing the `fields` field in v1 structs if there are no fields. This change allows Codama to recognize those types as struct types. The logic to default the fields is already in place, so this just allows it to be used.

fix: allow empty structs in v1 anchor to be parsed

---

.changeset/short-showers-shout.md
packages/renderers-rust/e2e/anchor/src/generated/accounts/guard_v1.rs
packages/renderers-rust/e2e/system/src/generated/accounts/nonce.rs
packages/renderers-rust/public/templates/accountsPage.njk

Fixes a few compiler errors from the `fetch` API for account state, produced by the Rust Renderer.
* If `Pubkey` is not imported in the base module, it's not available to the `fetch` feature either. Like other account state methods, use the full path qualifier.
* Fix a few clippy nits about unnecessary borrows.

Rust Renderer: `fetch` Fixes

---

.changeset/new-cycles-sip.md
packages/node-types/src/AccountNode.ts
packages/node-types/src/DefinedTypeNode.ts
packages/node-types/src/ErrorNode.ts
packages/node-types/src/InstructionAccountNode.ts
packages/node-types/src/InstructionArgumentNode.ts
packages/node-types/src/InstructionNode.ts
packages/node-types/src/InstructionRemainingAccountsNode.ts
packages/node-types/src/PdaNode.ts
packages/node-types/src/ProgramNode.ts
packages/node-types/src/contextualValueNodes/ResolverValueNode.ts
packages/node-types/src/pdaSeedNodes/VariablePdaSeedNode.ts
packages/node-types/src/typeNodes/OptionTypeNode.ts
packages/node-types/src/typeNodes/StructFieldTypeNode.ts
packages/nodes/src/InstructionNode.ts
packages/renderers-js-umi/src/getRenderMapVisitor.ts
packages/renderers-js-umi/src/getTypeManifestVisitor.ts
packages/renderers-js-umi/src/renderInstructionDefaults.ts
packages/renderers-js/src/fragments/instructionInputDefault.ts
packages/renderers-js/src/fragments/instructionInputResolved.ts
packages/renderers-js/src/fragments/instructionInputType.ts
packages/renderers-js/src/getTypeManifestVisitor.ts
packages/renderers-rust/src/getTypeManifestVisitor.ts
packages/renderers-vixen-parser/src/getTypeManifestVisitor.ts
packages/visitors-core/src/getResolvedInstructionInputsVisitor.ts

The `codama-nodes` Rust crate makes assumptions that many of the fields can be missing while still being readable. This PR marks many commonly missing fields, mainly docs, as optional to allow this to be the case.

Feat: mark more fields as optional

---

.changeset/hot-pots-push.md
packages/renderers-vixen-parser/e2e/meteora_parser/src/generated/instructions_parser.rs
packages/renderers-vixen-parser/public/templates/instructionsParserPage.njk
packages/renderers-vixen-parser/src/getRenderMapVisitor.ts

1. Add support to parse ixs with optional accounts 
2. It checks for programid as optionalAccountStrategy and then parse it as Some(a) or None
this will close #438

`feat` : Generate ix parsers with optional accounts

---

.changeset/sharp-pens-buy.md
packages/nodes-from-anchor/src/v00/typeNodes/TypeNode.ts
packages/nodes-from-anchor/src/v01/idl.ts
packages/nodes-from-anchor/src/v01/typeNodes/TypeNode.ts

I was using the latest version of Ray AMM（CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK） and found that it was not parsing this IDL correctly. The error is as follows:
```
/Users/ttt/code/jsrc/c001/node_modules/.pnpm/@codama+nodes-from-anchor@1.1.11_fastestsmallesttextencoderdecoder@1.0.22_typescript@5.8.3/node_modules/@codama/nodes-from-anchor/src/v00/typeNodes/TypeNode.ts:107
throw new CodamaError(CODAMA_ERROR__ANCHOR__UNRECOGNIZED_IDL_TYPE, {
^
CodamaError: Unrecognized Anchor IDL type [{"kind":"alias","value":{"array":["u64",8]}}].
at typeNodeFromAnchorV00 (/Users/ttt/code/jsrc/c001/node_modules/.pnpm/@codama+nodes-from-anchor@1.1.11_fastestsmallesttextencoderdecoder@1.0.22_typescript@5.8.3/node_modules/@codama/nodes-from-anchor/src/v00/typeNodes/TypeNode.ts:107:11)
at …
```

fix anchor00_alias

---

.changeset/strong-planes-hide.md
packages/nodes-from-anchor/README.md
packages/nodes-from-anchor/src/v00/InstructionNode.ts
packages/nodes-from-anchor/src/v00/ProgramNode.ts
packages/nodes-from-anchor/test/v00/InstructionNode.test.ts
packages/nodes-from-anchor/test/v00/ProgramNode.test.ts

This PR adds a default instruction discriminator for Shank idls, the generated value is a 1 byte discriminator at the start of the ix data based on the ix index value on the idl

Add support for default shank ix discriminators in nodes-from-anchor

---

README.md

This is mostly the same documentation, just reorganized:
- Add a section for impatient Anchor developers (this covers Codama'srelationship to Anchor, Solana Kit, web3.js, etc)
- Focus on creating IDL and then generating clients from the IDL, without first needing to understand design patterns and architecture.
- Use plainer language, eg 'create Clients' over 'render' etc.

Rework documentation

---

.changeset/stupid-bobcats-hug.md
packages/renderers-js/public/templates/fragments/instructionParseFunction.njk

This PR uses the `programId` optional account strategy as a fallback strategy to ensure the `getNextOptionalAccount` helper is always generated when optional account exist on the instruction.

[renderers-js] Fix missing `getNextOptionalAccount`

---

.changeset/purple-melons-lie.md
packages/renderers-rust/e2e/anchor/src/generated/accounts/guard_v1.rs
packages/renderers-rust/e2e/anchor/src/generated/instructions/create_guard.rs
packages/renderers-rust/e2e/anchor/src/generated/instructions/execute.rs
packages/renderers-rust/e2e/anchor/src/generated/instructions/initialize.rs
packages/renderers-rust/e2e/anchor/src/generated/instructions/update_guard.rs
packages/renderers-rust/e2e/dummy/src/generated/instructions/instruction3.rs
packages/renderers-rust/e2e/system/src/generated/instructions/advance_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate.rs
packages/renderers-rust/e2e/system/src/generated/instructions/allocate_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign.rs
packages/renderers-rust/e2e/system/src/generated/instructions/assign_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/authorize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/create_account_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/initialize_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol.rs
packages/renderers-rust/e2e/system/src/generated/instructions/transfer_sol_with_seed.rs
packages/renderers-rust/e2e/system/src/generated/instructions/upgrade_nonce_account.rs
packages/renderers-rust/e2e/system/src/generated/instructions/withdraw_nonce_account.rs
packages/renderers-rust/public/templates/accountsPage.njk
packages/renderers-rust/public/templates/instructionsPage.njk
packages/renderers-rust/src/getRenderMapVisitor.ts
packages/renderers-rust/src/utils/discriminatorConstant.ts
packages/renderers-rust/src/utils/index.ts

This PR exports a constant for each `DiscriminatorNode` attached to an account or instruction that has a value.
For instance,
```rust
pub const TRANSFER_SOL_DISCRIMINATOR: u32 = 2;
```
or 
```rust
pub const MY_ACCOUNT_DISCRIMINATOR: [u8; 8] = [185, 149, 156, 78, 245, 108, 172, 68];
```

[renderers-rust] Export discriminator constants for accounts and instructions

---

.changeset/salty-beans-check.md
packages/visitors-core/src/getByteSizeVisitor.ts
packages/visitors-core/test/getByteSizeVisitor.test.ts

This PR fixes an issue with the `getByteSizeVisitor` that wrongly assessed array-like nodes such as `ArrayTypeNode`, and `SetTypeNode` and `MapTypeNode`.

Fix size computation of array-like nodes

---

.changeset/true-readers-enter.md
packages/renderers-js/public/templates/fragments/typeDecoder.njk
packages/renderers-js/public/templates/fragments/typeEncoder.njk
packages/renderers-js/src/fragments/accountType.ts
packages/renderers-js/src/fragments/instructionData.ts
packages/renderers-js/src/fragments/typeCodec.ts
packages/renderers-js/src/fragments/typeDecoder.ts
packages/renderers-js/src/fragments/typeEncoder.ts
packages/renderers-js/src/fragments/typeWithCodec.ts
packages/renderers-js/src/getRenderMapVisitor.ts
packages/renderers-js/test/types/discriminatedUnions.test.ts

This PR adds type cast on generated encoder and decoder functions when dealing with fixed-size data enums. This is because the `getDiscriminatedUnion(Encoder|Decoder)` functions do not propagate the fixed-size information.
See #730

Use type cast on codecs of fixed-size data enums

---

.changeset/shaky-teeth-add.md
README.md
packages/visitors-core/README.md
packages/visitors-core/src/NodeSelector.ts
packages/visitors-core/src/bottomUpTransformerVisitor.ts
packages/visitors-core/src/topDownTransformerVisitor.ts
packages/visitors-core/test/NodeSelector.test.ts
packages/visitors/src/unwrapTupleEnumWithSingleStructVisitor.ts

- Callers now get the type `NodePath<Node>` instead of `Node[]`, which enables functions like `getLastNodeFromPath`
- Also updated the example in the README which treated the input as a `Node`
Closes #741

Use NodePath<Node> instead of Node[] for node selector function

---

.changeset/cold-cats-crash.md
packages/renderers/src/index.ts

This PR deprecates the exported functions of the `@codama/renderers` package in preparation to removing this umbrella package entirely.
Having such a package re-exporting renderers from various places not only makes versioning each renderer complicated, it also deincentivises consumers from finding community-maintained renderers.

Deprecate @codama/renderers package

---

.changeset/long-trees-fetch.md
packages/visitors-core/src/getByteSizeVisitor.ts
packages/visitors-core/test/getByteSizeVisitor.test.ts

Fix size computation of the `RemainderOptionTypeNode`. This node should always be of variable size unless the item it wraps is of size 0.

Fix size computation of `RemainderOptionTypeNode`

---

.changeset/nice-goats-grab.md
packages/visitors-core/src/getByteSizeVisitor.ts
packages/visitors-core/test/getByteSizeVisitor.test.ts

This PR adds a lot more test for the visitor that returns the size of a given type node. As such, it fixes some bugs and adds support for new use cases.
This is important because the JS renderer now uses this information to figure out if the generated codecs should be of type `FixedCodec` or simply `Codec`. Additionally, this work will be useful when adding a new `getMaxByteSizeVisitor` helper required by the upcoming Rust CPI renderer (using Pinocchio types).

Add more use-cases to byte size visitor

---

.changeset/purple-sites-behave.md
packages/visitors-core/src/getMaxByteSizeVisitor.ts
packages/visitors-core/src/index.ts
packages/visitors-core/test/getByteSizeVisitor.test.ts
packages/visitors-core/test/getMaxByteSizeVisitor.test.ts

This PR adds a new `getMaxByteSizeVisitor` helper that returns the maximum size in bytes a node can take, or `null` when no max size can be inferred.
This is slightly different to the existing `getByteSizeVisitor` that returns a number if and only if the node is of fixed size.
For instance, take the following node: `optionTypeNode(numberTypeNode("shortU16"))`.
Here the byte size visitor would return `null` because the `shortU16` number can take between 1 to 3 bytes and the option wrapper can either be of size `1` if the value is `None` or `size(x) + 1` if the value is `Some(x)`.
However, the max size visitor can understand that this node will take at most 4 bytes: 1 for the option prefix and 3 for the maximum value of a `shortU16`.

Add `getMaxByteSizeVisitor` helper

---

.changeset/light-ghosts-fall.md
packages/renderers-js/src/fragments/discriminatorCondition.ts

- **Remove redundant semicolon from generation of discriminator condition fragments**
- **Add changeset**
Although Prettier removes this if formatting is enabled, this ensures the render map visitor is generating valid code.

Remove redundant semicolon from generation of discriminator condition fragments

---

.changeset/cool-regions-clap.md
packages/node-types/src/shared/stringCases.ts

This PR changes the implementation of Codama's branded types so it uses exact values instead of TypeScript's `unique symbol`. This is to match [Kit's updated design](https://github.com/anza-xyz/kit/pull/473) and will allow multiple versions of the library to coexists.

Implement branded types without unique symbol
